tests: Better run_gtester.sh script.

diff --git a/tests/run_gtester.sh.in b/tests/run_gtester.sh.in
--- a/tests/run_gtester.sh.in
+++ b/tests/run_gtester.sh.in
@@ -1,5 +1,21 @@
+BINDIR="${CMAKE_BINARY_DIR}/tests/"
+RET=0
+
+function runtest {
+    gtester --keep-going "$1"
+    if [ $? -ne 0 ]; then  RET=$(($RET+1)) ; fi
+}
+
+# Go to source dir (so test would be able to use testdata/ in this dir)
 cd ${CMAKE_CURRENT_SOURCE_DIR}
-gtester ${CMAKE_BINARY_DIR}/tests/test_compression_wrapper
-gtester ${CMAKE_BINARY_DIR}/tests/test_load_metadata
-gtester ${CMAKE_BINARY_DIR}/tests/test_misc
-gtester ${CMAKE_BINARY_DIR}/tests/test_sqlite
+
+# Iterate over compiled tests
+for i in "$BINDIR"/test_*; do
+    # Run only executable regular files with "test_" prefix
+    if [ -f $i -a -x $i ]; then
+        runtest "$i"
+    fi
+done
+
+echo "Number of fails: $RET"
+exit $RET
